branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: ./CHANGELOG.md
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: "yarn package"
  - "@semantic-release/git"
  - - "@semantic-release/github"
    - assets:
        - path: "*.vsix"
          label: "Visual Studio Code Extension (.vsix)"
